/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    customers: CustomerAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    brands: Brand;
    media: Media;
    orders: Order;
    customers: Customer;
    'service-types': ServiceType;
    'service-requests': ServiceRequest;
    pages: Page;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'service-types': ServiceTypesSelect<false> | ServiceTypesSelect<true>;
    'service-requests': ServiceRequestsSelect<false> | ServiceRequestsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Customer | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL segment. Leave blank to generate from the name/title.
   */
  slug?: string | null;
  priceKES: number;
  /**
   * Original price — shown struck-through to signal a discount.
   */
  compareAtPriceKES?: number | null;
  sku?: string | null;
  stockQty: number;
  /**
   * One or two lines shown on product cards and search results.
   */
  shortDescription?: string | null;
  /**
   * Full product description.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "1 year manufacturer warranty".
   */
  warranty?: string | null;
  status?: ('draft' | 'active' | 'archived') | null;
  category?: (number | Category)[] | null;
  brand?: (number | null) | Brand;
  /**
   * Show in the "Featured" section on the homepage.
   */
  featured?: boolean | null;
  /**
   * Auto-set when stock is at or below 3.
   */
  lowStock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL segment. Leave blank to generate from the name/title.
   */
  slug?: string | null;
  /**
   * Optional — for sub-categories.
   */
  parent?: (number | null) | Category;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Show in the main navigation menu.
   */
  showInNav?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  navOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * URL segment. Leave blank to generate from the name/title.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  /**
   * Linked account (blank for guest checkout).
   */
  customer?: (number | null) | Customer;
  contactName: string;
  contactPhone: string;
  contactEmail?: string | null;
  /**
   * Snapshot of what was ordered — prices are frozen at checkout time.
   */
  items: {
    product?: (number | null) | Product;
    title: string;
    sku?: string | null;
    unitPriceKES: number;
    qty: number;
    id?: string | null;
  }[];
  deliveryMethod: 'pickup' | 'nairobi' | 'countrywide';
  deliveryFeeKES?: number | null;
  shippingAddress?: {
    recipient?: string | null;
    phone?: string | null;
    town?: string | null;
    area?: string | null;
    details?: string | null;
  };
  subtotalKES?: number | null;
  totalKES?: number | null;
  paymentMethod: 'paystack' | 'mpesa_stk' | 'manual_mpesa' | 'bank_transfer' | 'cash_on_delivery';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * Provider transaction reference.
   */
  paymentReference?: string | null;
  paidAt?: string | null;
  /**
   * Set once stock has been decremented for this order.
   */
  stockApplied?: boolean | null;
  paymentMeta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fulfillmentStatus: 'processing' | 'packed' | 'dispatched' | 'delivered' | 'cancelled';
  /**
   * Internal notes.
   */
  notes?: string | null;
  /**
   * Automatic history of status changes and notes.
   */
  timeline?:
    | {
        at: string;
        event: string;
        note?: string | null;
        /**
         * Staff member or "system".
         */
        by?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  /**
   * Kenyan format, e.g. 0712345678 or +254712345678.
   */
  phone: string;
  addresses?:
    | {
        label?: string | null;
        recipient: string;
        phone: string;
        town: string;
        area?: string | null;
        details?: string | null;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes (not visible to the customer).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types".
 */
export interface ServiceType {
  id: number;
  name: string;
  /**
   * URL segment. Leave blank to generate from the name/title.
   */
  slug?: string | null;
  /**
   * Short line shown on the services grid.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Indicative starting price shown as "from KES …". Leave blank for "Request a quote".
   */
  basePriceFromKES?: number | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests".
 */
export interface ServiceRequest {
  id: number;
  requestNumber?: string | null;
  status: 'new' | 'quoted' | 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
  serviceType: number | ServiceType;
  assignedTechnician?: (number | null) | User;
  /**
   * Linked account (blank if submitted as a guest).
   */
  customer?: (number | null) | Customer;
  contactName: string;
  contactPhone: string;
  contactEmail?: string | null;
  siteAddress: {
    town: string;
    area?: string | null;
    details?: string | null;
  };
  description: string;
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  preferredDate?: string | null;
  quote?: {
    lineItems?:
      | {
          label: string;
          qty: number;
          unitPriceKES: number;
          id?: string | null;
        }[]
      | null;
    labourKES?: number | null;
    totalKES?: number | null;
    /**
     * Amount payable up front to book.
     */
    depositKES?: number | null;
    depositPaid?: boolean | null;
    validUntil?: string | null;
    depositReference?: string | null;
    acceptedAt?: string | null;
  };
  scheduledStart?: string | null;
  scheduledEnd?: string | null;
  /**
   * Technician notes after the visit.
   */
  visitReport?: string | null;
  /**
   * Automatic history of status changes and notes.
   */
  timeline?:
    | {
        at: string;
        event: string;
        note?: string | null;
        /**
         * Staff member or "system".
         */
        by?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin: full access. Manager: catalog + orders + services. Sales: orders. Technician: assigned jobs only.
   */
  role: 'admin' | 'manager' | 'sales' | 'technician';
  /**
   * Used for job notifications / WhatsApp.
   */
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment. Leave blank to generate from the name/title.
   */
  slug?: string | null;
  intro?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'service-types';
        value: number | ServiceType;
      } | null)
    | ({
        relationTo: 'service-requests';
        value: number | ServiceRequest;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  priceKES?: T;
  compareAtPriceKES?: T;
  sku?: T;
  stockQty?: T;
  shortDescription?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  warranty?: T;
  status?: T;
  category?: T;
  brand?: T;
  featured?: T;
  lowStock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  image?: T;
  showInNav?: T;
  navOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  items?:
    | T
    | {
        product?: T;
        title?: T;
        sku?: T;
        unitPriceKES?: T;
        qty?: T;
        id?: T;
      };
  deliveryMethod?: T;
  deliveryFeeKES?: T;
  shippingAddress?:
    | T
    | {
        recipient?: T;
        phone?: T;
        town?: T;
        area?: T;
        details?: T;
      };
  subtotalKES?: T;
  totalKES?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  paymentReference?: T;
  paidAt?: T;
  stockApplied?: T;
  paymentMeta?: T;
  fulfillmentStatus?: T;
  notes?: T;
  timeline?:
    | T
    | {
        at?: T;
        event?: T;
        note?: T;
        by?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  addresses?:
    | T
    | {
        label?: T;
        recipient?: T;
        phone?: T;
        town?: T;
        area?: T;
        details?: T;
        isDefault?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types_select".
 */
export interface ServiceTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  basePriceFromKES?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  active?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests_select".
 */
export interface ServiceRequestsSelect<T extends boolean = true> {
  requestNumber?: T;
  status?: T;
  serviceType?: T;
  assignedTechnician?: T;
  customer?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  siteAddress?:
    | T
    | {
        town?: T;
        area?: T;
        details?: T;
      };
  description?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  preferredDate?: T;
  quote?:
    | T
    | {
        lineItems?:
          | T
          | {
              label?: T;
              qty?: T;
              unitPriceKES?: T;
              id?: T;
            };
        labourKES?: T;
        totalKES?: T;
        depositKES?: T;
        depositPaid?: T;
        validUntil?: T;
        depositReference?: T;
        acceptedAt?: T;
      };
  scheduledStart?: T;
  scheduledEnd?: T;
  visitReport?: T;
  timeline?:
    | T
    | {
        at?: T;
        event?: T;
        note?: T;
        by?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  slides?:
    | {
        image: number | Media;
        heading: string;
        subheading?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Category tiles shown below the hero. Leave blank to auto-pick nav categories.
   */
  featuredCategories?: (number | Category)[] | null;
  promoStrip?: {
    enabled?: boolean | null;
    text?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  testimonials?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  whyChooseUs?:
    | {
        title: string;
        body: string;
        icon?: ('shield' | 'truck' | 'wrench' | 'headset' | 'badge-check' | 'clock') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Scrolling bar at the very top of the site. Leave blank to hide.
   */
  announcement?: string | null;
  phone?: string | null;
  /**
   * Number for the floating WhatsApp button and "enquire" links.
   */
  whatsapp?: string | null;
  email?: string | null;
  addressLine?: string | null;
  /**
   * Google Maps link or embed URL.
   */
  mapUrl?: string | null;
  hours?: string | null;
  socials?:
    | {
        platform?: ('facebook' | 'instagram' | 'tiktok' | 'x' | 'youtube' | 'linkedin') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the delivery page and used as defaults at checkout.
   */
  deliveryRates?:
    | {
        label: string;
        feeKES: number;
        id?: string | null;
      }[]
    | null;
  trustBadges?:
    | {
        title: string;
        subtitle?: string | null;
        icon?: ('truck' | 'shield' | 'headset' | 'badge-check' | 'credit-card' | 'wrench') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        heading?: T;
        subheading?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  featuredCategories?: T;
  promoStrip?:
    | T
    | {
        enabled?: T;
        text?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  whyChooseUs?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcement?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  addressLine?: T;
  mapUrl?: T;
  hours?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  deliveryRates?:
    | T
    | {
        label?: T;
        feeKES?: T;
        id?: T;
      };
  trustBadges?:
    | T
    | {
        title?: T;
        subtitle?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}